version: "3.1"
services: 

  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: TimeTracker
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    image: strohscd/timetracker-api:${TIMETRACK_TAG:-latest}
    restart: always
    environment:
      BotToken: BotTokenHere
    depends_on: 
      - db

  frontend:
    image: strohscd/timetracker-frontend:${TIMETRACK_TAG:-latest}
    restart: always
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./certbot-data:/etc/letsencrypt/
    depends_on: 
      - db
      - api

volumes:
  postgres-data:
    driver: local
  certbot-data:
    driver: local